<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>MdLight</AssemblyName>
    <RootNamespace>MdLight</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Version>0.2.0</Version>
    <Authors>rausNT</Authors>
    <Description>Lightweight Markdown viewer for Windows.</Description>
    <Product>MdLight</Product>
    <Copyright>Copyright © 2026 rausNT</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
</Project>
